project:
  type: website

website:
  title: "is415-gaa-grp12"
  navbar:
    left:
    - text: "Analysis"
      menu:
        - text: "Spatial Point Pattern Analysis"
          href: "analysis/SPPA/SPPA.html"
        - text: "Network Constrained SPPA"
          href: "analysis/Network-Constrained/Network-Constrained.html"
        
    - text: "Proposal"
      href: "proposal/proposal.html"
    - text: "Research Report"
      href: "report/Research_Report.html"
    - text: "User Guide"
      href: "user_guide/user_guide.html"
    right:
      - href: index.qmd
        text: Home
        
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

