project:
  type: website

website:
  title: "is415-gaa-grp12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "proposal/proposal.html"
        text: Proposal
      - href: "analysis/Data.html"
        text: "Data Wrangling"
      - href: "analysis/SPPA.html"
        text: "Spatial Point Pattern Analysis"
      - href: "analysis/Network-Constrained.html"
        text: "Network Constrained SPPA"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

